path:
  repo: /home/cosine/mygit/linux    #repo path
  output_diff: /home/cosine/cveresult/diff  #output folder path
  output_goodfunction: /home/cosine/cveresult/goodfunction
  output_bedfunction: /home/cosine/cveresult/bedfunction
#select keywords in commit descirption
keyword: 'CVE-'
#limit the time range of commit
time:
  from: 2010-01-01
  to: 2018-05-17
#the files need to save
savefile:
  diff: True   #diff file
  a_file: True   #the file unpatched
  b_file: True   #the file patched
  description: True   #description about the commit
  keeptype: True   #Weather you want to keep the type of file patched 
#filter the commit
filter:
  maxdiffsnum: 10
  maxchangeline: 20
#You'd better not change the para
pagesize: 100000
